version: '3.8'

services:
  web:
    build: .
    ports:
      - "50060:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      command: flask run --host=0.0.0.0 --port=5000