version: '3.8'

services:
  php:
    build: ./php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - 50010:80

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_injection1
      MYSQL_USER: kitsec
      MYSQL_PASSWORD: kitsec
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 50050:100
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
  
volumes:
  db_data: