version: '3.8'
services:
  web:
    build: .
    ports:
      - "50100:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 
