version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50050:80"
    volumes:
      - .:/app
    environment:
      - FLAG=kitsec{di_rec_tory_tra_versa_l}
